# Generated by Django 4.1.7 on 2023-03-22 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_transformer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformer',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='transformer',
            name='code',
            field=models.TextField(blank=True, default='False', null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transformer',
            name='is_public',
            field=models.CharField(blank=True, default='False', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
