# Generated by Django 4.1.7 on 2023-03-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_text_transformer_description_transformer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
