# Generated by Django 4.1.7 on 2023-03-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_transformer_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
