# Generated by Django 4.1.7 on 2023-03-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_task_target_task_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='target',
            new_name='targets',
        ),
    ]
