# Generated by Django 4.1.7 on 2023-04-07 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_task_daily_time_task_minute_time_task_schedule_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('task', models.CharField(default='', max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_run',
        ),
        migrations.AddField(
            model_name='task',
            name='last_run_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='last_run_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='StandBy', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Scheduler',
        ),
    ]
