# Generated by Django 4.1.7 on 2023-04-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_logs_remove_task_last_run_task_last_run_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='Shutdown', max_length=50, null=True),
        ),
    ]
