# Generated by Django 4.1.7 on 2023-04-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_task_source_alter_task_status_task_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='transformer_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
