# Generated by Django 4.1.7 on 2023-04-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_transformer_transformer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='stopped', max_length=50, null=True),
        ),
    ]
