# Generated by Django 4.1.7 on 2023-04-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='weekly_day',
            new_name='fri',
        ),
        migrations.AddField(
            model_name='task',
            name='mon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sun',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='thu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='wed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
