# Generated by Django 4.1.7 on 2023-04-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_rename_weekly_day_task_fri_task_mon_task_sat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
