# Generated by Django 4.1.7 on 2023-05-05 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_task_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Running_Jobs',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('job', models.TextField(default='')),
                ('last_run_date', models.DateField(default=django.utils.timezone.now)),
                ('last_run_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
