# Generated by Django 4.1.7 on 2023-07-07 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_running_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(blank=True, max_length=200, null=True)),
                ('filetype', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='TaskConnectorData',
            fields=[
                ('task_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('time_created', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='connector',
            name='can_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='can_target',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='type_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(default='01', max_length=200),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='transformer_type',
            field=models.CharField(blank=True, default='Python', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='files',
            field=models.ManyToManyField(to='customer.filesmodel'),
        ),
    ]
