# Generated by Django 4.1.7 on 2023-07-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_filesmodel_taskconnectordata_connector_can_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(blank=True, max_length=200, null=True)),
                ('filetype', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('ingest', models.CharField(default=False, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='connector',
            name='files',
        ),
        # migrations.DeleteModel(
        #     name='FilesModel',
        # ),
    ]
