# Generated by Django 4.1.7 on 2023-07-12 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_filemodels_remove_connector_files_delete_filesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_date_update', models.DateField(default=django.utils.timezone.now)),
                ('last_time_update', models.TimeField(default=django.utils.timezone.now)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.connector')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.task')),
            ],
        ),
        migrations.DeleteModel(
            name='FilesModel',
        ),
    ]
