# Generated by Django 4.1.7 on 2023-07-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_connections_delete_filesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='task',
        ),
        migrations.AddField(
            model_name='connections',
            name='pipelines',
            field=models.ManyToManyField(blank=True, null=True, related_name='pipelines_task', to='customer.task'),
        ),
    ]
