# Generated by Django 4.1.7 on 2023-07-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_remove_connections_task_connections_pipelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='chat_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
