# Generated by Django 4.1.7 on 2023-07-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_botfileuploads_chatbot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='connections',
            new_name='connection',
        ),
    ]
