# Generated by Django 4.1.7 on 2023-07-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_rename_connections_chatbot_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='api_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
