# Generated by Django 4.1.7 on 2023-08-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_chatbot_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_version',
            field=models.CharField(default='free', max_length=100),
        ),
    ]
