# Generated by Django 4.1.7 on 2023-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_customer_product_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chat_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
