# Generated by Django 4.1.7 on 2023-08-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_chatbot_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='share_count',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
