# Generated by Django 4.1.7 on 2023-08-25 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_chatbot_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
