# Generated by Django 4.1.7 on 2023-09-03 04:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0034_prompt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompt',
            new_name='Prompts',
        ),
    ]
