# Generated by Django 4.1.7 on 2023-09-03 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_rename_prompt_prompts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompts',
            name='chatbot',
        ),
        migrations.AddField(
            model_name='prompts',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.connections'),
        ),
    ]
