# Generated by Django 4.1.7 on 2023-09-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_remove_prompts_chatbot_prompts_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompts',
            old_name='configs',
            new_name='content',
        ),
    ]
