# Generated by Django 4.1.7 on 2023-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_rename_configs_prompts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='is_public',
            field=models.CharField(blank=True, default='False', max_length=20, null=True),
        ),
    ]
