# Generated by Django 4.1.7 on 2023-09-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_prompts_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='like',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
