# Generated by Django 4.1.7 on 2023-09-08 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_prompts_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='running_jobs',
            name='next_run_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='running_jobs',
            name='next_run_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
