# Generated by Django 4.1.7 on 2023-09-08 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_running_jobs_next_run_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='running_jobs',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.task'),
        ),
    ]
