# Generated by Django 4.1.7 on 2023-09-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_running_jobs_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='running_jobs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
