# Generated by Django 4.1.7 on 2024-07-11 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.connector'),
        ),
    ]
