# Generated by Django 4.1.7 on 2024-07-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_chathistory_connector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='chat_history',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
