# Generated by Django 4.1.7 on 2024-07-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_remove_chathistory_chat_history_chathistory_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
