# Generated by Django 4.1.7 on 2024-07-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_chathistory_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='id',
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='api_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
