# Generated by Django 4.1.7 on 2024-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_remove_chatbot_id_alter_chatbot_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
