# Generated by Django 4.1.7 on 2023-06-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_connector_type_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='id',
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
